substitutions:
  _REPOSITORY: dev-repo
  _SERVICE_NAME: react-frontend

steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest'
      - '--builder'
      - 'gcr.io/buildpacks/builder:google-22'
      - '--network'
      - 'cloudbuild'
      - '--publish'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest'
      - '--region'
      - '$LOCATION'
      - '--project'
      - '$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
